# Conclusion

Simply, Democratic states tend to benefit under Democratic presidents, and Republican states tend to benefit under Republican presidents. However, these patterns and findings do not overwhelmingly show consistent improvement across all states and all variables. Certain variables, such as the unemployment rate, tend to show stronger trends within and across states, while variables like personal consumption expenditure yield mixed findings. Additionally, certain states like Oklahoma, Wyoming, South Dakota, North Dakota, and Nebraska follow stronger trends in economic differences across administrations, while other states have very mixed results. Also, certain variables show different state patterns, with the unemployment rate impacting Republican states more and the median household income impacting Democratic states more. 

In the future, it will be useful to analyze the natural state grouping that this analysis began to uncover. For example, the grouping of middle-of-the-state states or the cluster of PCA states. A small industry-specific analysis was conducted during the unemployment rate analysis, but it began to analyze ideas and trends not related to the original research question, so it was ultimately not included. However, that would be an insightful future direction in analyzing the impact of the natural groupings of states compared to the voting preferences of the states. 

The analysis encountered a few limitations, which were addressed with feature engineering and acknowledging necessary assumptions. Overall, this project was insightful in understanding the importance of robust preprocessing pipelines, especially when working with diverse datasets and visualization types. For example, many visualizations required data transformation, so having clean code that did not override changes was essential to an efficient workflow. 

