# Data

## Description

The data for this project has been pulled from various government databases. The first dataset is from the United States census and contains median salary values broken down by ethnicity and gender from the years 2000 to 2024 ([Historical Income Tables: People](https://www.census.gov/data/tables/time-series/demo/income-poverty/historical-income-people.html)). The United States Census obtains yearly data through randomized surveys of thousands of American households and, with those results and government records, estimates population-sized values. 


The second dataset is from the United States Bureau of Economic Analysis and contains information on each state's GDP, per capita personal income, and employment from 2001 to 2024 ([Economic Factors by State](https://www.bea.gov/data/income-saving/personal-income-by-state)). The Bureau of Economic Analysis obtains most of its data from Census Bureau surveys or federal administration surveys.  


The third dataset, from the Federal Reserve Bank of St. Louis (FRED), contains median household income data for each state from 2001 to 2024 ([Median Income by State](https://fred.stlouisfed.org/release/tables?eid=259515&rid=249)). The dataset has 53 columns, including "Year", all 50 states, the District of Columbia, and the United States average, and 23 rows spanning 2001 through 2024. 


The last dataset from the Rhode Island Department of Labor and Training contains the unemployment rate for each state from 2000 to 2024 ([Unemployment Rate by State](https://dlt.ri.gov/labor-market-information)). The dataset has 25 columns, including "State" and the years 2000 through 2024, and 52 rows, including all fifty states, the District of Columbia, and the United States average.  


This project also plans to reference, but not directly use, election result data. This data will consist of the percentage of the state that voted for each major party, and the percentage of each sex and ethnicity that voted for each major party, for each election from 2000 to 2024. 

This paragraph will describe some potential limitations and issues with the data. First, some of the data sources are not corrected for inflation. This means that monetary values between years are not completely comparable. To avoid misleading results, the analysis may explore differences between years for every state or manually adjust certain features for inflation. Secondly, for ethnic demographic data, many ambiguous assumptions exist for users filling out surveys. This means there may be inconsistencies with how survey-takers interpret or answer the questions. Data related to the sex or ethnicity of United States citizens may not be included in the final analysis due to comparison limitations (demographic breakdowns may not be available for early elections) and potential biases in the survey data. 

## Missing value analysis
