# Introduction

Political polarization in the United States has greatly intensified throughout the twenty-first century. In fact, partisan hatred, which is intense dislike for the opposite party, has increased substantially from the late twentieth century to the mid 2010’s, with negative sentiment toward the other party’s ideology nearly doubling among members of both major parties during that period.^[See Pew Research Center, "Political Polarization in the American Public," 2014.]

In the United States, the two major political parties, Democrats and Republicans, dominate every presidential election cycle. In the twenty-first century (excluding the 2024 presidential election), there have been six elections, resulting in four different administrations: two Democratic and two Republican. Each party also has “safe states,” which are states that have voted for the same party over the last six elections, often by large margins.

This project explores economic statistics for safe states at the state-by-state level from 2001 to 2024 (covering the Bush, Obama, Trump, and Biden administrations). The goal of this project is to explore whether a state that consistently votes for the same party in every presidential election experiences stronger economic outcomes during that party’s administrations compared to during the other party’s administrations. On a larger scale, this project aims to understand if political polarization is warranted, specifically, whether consistently voting for the same party aligns with measurable positive economic outcomes, or if states experience more similar economic trends than their political identities would suggest. The analysis will also analyze natural economic differences in Democratic and Republican states to help contextualize findings. 
